### ISSUE TITLE
Is it possible to define user mappings?

### ISSUE THREAD

**Issue by blasco** [tpope/vim-commentary#115]
I would like to to disable the default mappings and define my own. Is this currently supported?

**Comment by tpope** [comment]
Create your own map to `<Plug>Commentary` *and* map something else on `gc` and the built-in will be disabled.

**Comment by GeertRoks** [comment]
Hi, This still doesn't work for me. My remap looks like this: `nnoremap cm <Plug>Commentary`. However it doesn't allow me to use the motions and text objects, like `gcip` for comment inner paragraph. I am not great at vimscript, so am I missing something?

My result for `:nmap`:
~~~
n  cm          * <Plug>Commentary
n  gc            <Plug>Commentary
~~~
What does the `*` mean in front of the `<Plug>Commentary` at the `cm` binding?

`gc` still works with text objects and motions, but `cmip` for example goes into `insert` and types a letter `p`. So `cm` doesn't do anything in this command.

How can I make this remap work with the motions and text objects?

**Comment by chrisbra** [comment]
> nnoremap cm <Plug>Commentary

You want the mapping to be further resolved, so do **not** use *nnore*map

**Comment by GeertRoks** [comment]
Thanks @chrisbra! I got it working now

The solution is to use `nmap` instead of `nnoremap`. If I understand correctly, this makes the mapping recursive and thus as @chrisbra said, it allows the mapping to be further resolved.

The `*` is now also gone when I type `:nmap`. Still don't really sure what it means, but I guess it has something to do with if the mapping is recursive or not.

**Comment by tpope** [comment]
See `:help map-listing` for an explanation of symbols like `*`.
