### ISSUE TITLE
Fails to uncomment lines that are padded with empty comments.

### ISSUE THREAD

**Issue by marblenix** [tpope/vim-commentary#31]
Steps to reproduce: 

```
vim test.sh
```

```
i
#
# This is a test
#
# ohai
#<ESC>gcap
```

The following works as intended:
```
i
# This is a test
# ohai<ESC>gcap
```

**Comment by RobertAudi** [comment]
I encountered this bug a couple times myself. The only time that it is a blocking point is when trying to comment out a whole block of code that includes an empty commented line. One example would be documentation comments before a method. 
Another scenario is when trying to comment out a whole file; when it doesn't work it's often disorienting because it fails silently.
