### ISSUE TITLE
Would it be possible to support an optional keybinding?

### ISSUE THREAD

**Issue by toranb** [tpope/vim-commentary#36]
https://github.com/tpope/vim-commentary/blob/master/plugin/commentary.vim#L84

Currently you need to use the gc shortcut (or \ for legacy devs like me). Would you ever be willing to make this an optional "setting" so users could modify it in their vimrc? I find when I'm remote pairing w/ java or c# developers they commonly like a "jetbrains" set of shortcuts to stay productive. If I could optionally update this binding (or supply another alongside what I have with gc) it would go a long way.

Thanks for such a great plugin and all your awesome vim community work! This project (and vim itself) has helped make me personally more productive year after year :)

**Comment by Netznarkose** [comment]
As discussed in this issue I added following binding `map <C-m> <plug>Commentary` to my vimrc which works fine. But unfortunately I can't open files from the quickfix anymore because the return key is gone. If I type this ex-command `:verbose map <CR>` I see this message `<CR>          <Plug>Commentary`
any Ideas how to solve this?

**Comment by tpope** [comment]
CTRL-M *is* carriage return. Your only recourse is to pick another key.
