### ISSUE TITLE
Commenting js code inside HTML files

### ISSUE THREAD

**Issue by kevinisaac** [tpope/vim-commentary#60]
In a HTML file, while commenting a code with `gcc` inside a `<script></script>` tag, it uses `<!---->` to mark comments instead of the JS style comment marker `//`.

**Comment by vheon** [comment]
vim-commentary is designed to be really simple, so it doesn't automatically detect that you're in an embedded language. You have a couple of options:

- Change plugin and go for something more complex like https://github.com/tomtom/tcomment_vim or https://github.com/scrooloose/nerdcommenter (I've never used them but I seem to remember that those support your use case)
- Find a way to change the `commentstring` setting depending on the cursor position; I think you can use https://github.com/Shougo/context_filetype.vim for that.
- Use something like https://github.com/AndrewRadev/inline_edit.vim which allows you to call the `: InlineEdit` command and it lets you work on the embedded language in a buffer with a proper filetype and all the ftplugin and settings for that filetype, like the `commentstring` option.

I would go for option 3 since it brings really more power to editing embedded language because all the plugins and proper settings will be used, but is your choice.

**Comment by kevinisaac** [comment]
@vheon Thanks for the alternative ways of achieving this functionality. Although inline_edit.vim looks cool, I don't think it is the perfect tool for my scenario. I think I'll go with the second option.

**Comment by specious** [comment]
As mentioned in #9, [suy/vim-context-commentstring](https://github.com/suy/vim-context-commentstring) works perfectly.

**Comment by KngZhi** [comment]
for neovim and for ts coder, it's recommended to use [nvim-ts-context-commentstring](https://github.com/JoosepAlviste/nvim-ts-context-commentstring)
